### ISSUE TITLE
Documentation - Security Implications

### ISSUE THREAD

**Issue by cwaldbieser** [FreshSupaSulley/DuOSU#1]
I am an IAM practitioner whose organization uses Duo.  This project sounds interesting, but I have some questions about the security implications of how this software operates, and there doesn't seem to be an FAQ.

If I understand correctly, this project creates a browser extension that registers itself as a kind of virtual DUO mobile device, so you don't need a physical phone or tablet.  Presumably, this virtual device runs in the same browser as the protected web site.

The whole point of multi-factor authentication is to require another method of authentication beyond the traditional "something you know" (i.e. your username and password).  Duo mobile is supposed to represent "something you have" (e.g. a phone or tablet). 

Does the "virtual Duo device" created by this extension act as a different authentication factor?

At my organization, before we rolled out Duo, we went from having anywhere from 20-50 compromised email accounts per month to zero compromised accounts per month after we rolled out Duo.  The majority of our users use Duo Mobile, but we have a fair number that use phone/SMS and a tiny number that use WebAuthN/security keys.  This was because phishing campaigns and breaches of 3rd party sites where users reused their passwords routinely netted user credentials.  Bad actors would simply use the credentials (something *they* know) to authenticate to the compromised account.  Once Duo was in place, an attacker could enter the credentials, but they wouldn't be able to perform the Duo authentication (using phone, app, or webauthn).  So in that kind of scenario, it seems like this extension behaves similar to a physical device.  An attacker that phishes your password likely won't have access to your browser and thus won't be able to access a protected site.

Of course, there are other attack vectors like cross-site scripting (XSS).  I'm not super familiar with the browser extension security model, so I'd appreciate if you or anyone else could weigh in on whether there is enough separation between the site and the extension to be considered different security contexts.

Any additional documentation or discussion on the security aspect of this extension would be appreciated.

**Comment by FreshSupaSulley** [comment]
What an honor to have an IAM practitioner reviewing this!

**Comment by FreshSupaSulley** [comment]
You have a good understanding of how the extension works!
DuOSU is indeed a "virtual Duo device" that acts as a legitimate 2-factor authenticator. The scenario you mentioned is accurate; a hacker would need their victim's login credentials and have access to the user's browser to gain access.

With that said, it's important I mention the security vulnerabilities introduced by DuOSU:
1. **The hacker could time their login in sync with the user**. Because DuOSU approves **all push requests** when clicked, if an attacker were to steal their victim's account information and try to log in at the same time the user clicks the extension (~30-second window before their push request expires), they would be able to gain access.
2. **The user could be socially engineered**. DuOSU provides the ability for users to export their login data to use it on another extension. The user could be socially engineered to send a hacker their login data.
3. **The user's Google account could be compromised**. DuOSU uses the browser's storage sync API to keep information synced to their account. This means that all browsers the user is signed into share the same DuOSU login data (this can be changed according to the account's sync policy). If the hacker has access to the user's Google account and their login credentials, they could gain access as well.

While these scenarios are possible, they're unlikely. The hacker would need to obtain their victim's login credentials _and_ have knowledge that their victim uses the extension. A foreign hacker would be no way of knowing this without some sort of inside information.

As for security concerns of extensions themselves, there isn't need for alarm. Google Chrome and Firefox use a system of "Isolated Worlds" to separate extensions from each other and from web page JavaScript. It's ensured by the browser that extensions cannot be accessed in any way by malicious JavaScript code (you can read more [here](https://developer.chrome.com/docs/extensions/mv3/content_scripts/#isolated_world)).

In conclusion, there is enough separation between websites and the extension to be considered different security contexts.

Thank you for bringing this to my attention. I'll add a FAQ about the security implications.

**Comment by FreshSupaSulley** [comment]
After analyzing these issues above, I've discovered this extension's primary security threat:

"1. **The hacker could time their login in sync with the user**. Because DuOSU approves **all push requests** when clicked, if an attacker were to steal their victim's account information and try to log in at the same time the user clicks the extension (~30-second window before their push request expires), they would be able to gain access."

I'm currently working on a patch that would prompt the user if more than one push request is active. In this scenario, the user is warned and has the ability to approve the push request that belongs to them by comparing their IP addresses, locations, etc. This would protect a user from trial-and-error attacks, where the attacker hopes the user would approve both their login and the user's at the same time.

**Comment by FreshSupaSulley** [comment]
The patch is now uploaded and is being reviewed by the Chrome development team.

Patch notes:
- DuOSU no longer mass approves all push requests at any point.
- Auto-Login was removed due to the possibility that a hacker could, by pure chance, log in through Duo at the same time as the user. This was possible because Auto-Logins would approve all login attempts at once if the user was on the login page.
- If more than 1 push request is active at a time, DuOSU warns the user and allows them to compare locations, IP addresses, and integrations of the logins to weed out unauthorized attempts.
- Push request information is now displayed upon every successful login (location, IP address, integration, etc.).

The extension security model is quite strong: no malicious scripts or websites can force DuOSU to approve push requests OR extract the login data it uses to authenticate with Duo. The largest security concern was my failure to recognize the security threats created by DuOSU. I'm very glad you took the time to open this issue!

I hope this thread reassures you of Chrome's extension security and of this extension's security practices.
